### ISSUE TITLE
Jenkins tests are failing - systemd dependency

### ISSUE THREAD

**Issue by simonrankine** [bbc/nmos-mdns-bridge#2]
Jenkins tests currently fail because of missing systemd dependency

https://jenkins.rd.bbc.co.uk/job/ap.python-service-nmos-mdns-bridge/20/console

**Comment by andrewbonney** [comment]
Resolved the systemd issue, but now it's failing due to mock, which I'm assuming is a version related issue. We should probably get this one using virtualenv now that it's working properly on Jenkins.

**Comment by andrewbonney** [comment]
Should be resolved by #5

**Comment by andrewbonney** [comment]
Closing this one as I believe the issue in #7 is causing the remaining problems.
